### ISSUE TITLE
Ruby 3.0 Support

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-ietf#132]
https://github.com/metanorma/metanorma-cli/pull/233/checks?check_run_id=2129377527

```
  5) Metanorma::Cli::Compiler.compile compile with errors
     Failure/Error:
       expect do
         Metanorma::Cli.start(["spec/fixtures/mn-samples-ietf-antioch.adoc", "--no-install-fonts"])
       end.to raise_error SystemExit

       expected SystemExit, got #<Errno::ENOENT: No such file or directory @ rb_sysopen - https://tools.ietf.org/wg/> with backtrace:
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:48:in `initialize'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:48:in `open'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:48:in `cache_workgroup_ietf'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:75:in `block in cache_workgroup'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:74:in `open'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/validate.rb:74:in `cache_workgroup'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.2.9/lib/asciidoctor/ietf/converter.rb:23:in `makexml'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:142:in `document'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
         # ./vendor/bundle/ruby/3.0.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
         # ./vendor/bundle/ruby/3.0.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-1.2.7/lib/metanorma/input/asciidoc.rb:24:in `process'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-1.2.7/lib/metanorma/processor.rb:24:in `input_to_isodoc'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:137:in `process_input'
         # ./vendor/bundle/ruby/3.0.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:24:in `compile'
         # ./lib/metanorma/cli/compiler.rb:45:in `compile_file'
         # ./lib/metanorma/cli/compiler.rb:30:in `compile'
         # ./lib/metanorma/cli/compiler.rb:35:in `compile'
         # ./lib/metanorma/cli/command.rb:211:in `compile_document'
         # ./lib/metanorma/cli/command.rb:46:in `block in compile'
         # ./lib/metanorma/cli/command.rb:46:in `each'
         # ./lib/metanorma/cli/command.rb:46:in `compile'
         # ./vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         # ./vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         # ./vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         # ./vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
         # ./lib/metanorma/cli.rb:67:in `start'
         # ./spec/metanorma/cli/compiler_spec.rb:29:in `block (5 levels) in <top (required)>'
         # ./spec/metanorma/cli/compiler_spec.rb:28:in `block (4 levels) in <top (required)>'
         # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
         # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr.rb:188:in `use_cassette'
         # ./spec/metanorma/cli/compiler_spec.rb:27:in `block (3 levels) in <top (required)>'
         # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
         # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
     # ./spec/metanorma/cli/compiler_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # ./vendor/bundle/ruby/3.0.0/gems/vcr-5.0.0/lib/vcr.rb:188:in `use_cassette'
     # ./spec/metanorma/cli/compiler_spec.rb:27:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
```

**Comment by CAMOBAP** [comment]
Doesn't reproduces anymore
