### ISSUE TITLE
Failure to cite OMG documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#145]
Reported by @douglm

```adoc
* [[[BPMN,OMG BPMN 2.0.2]]], Object Management Group, Business Process Model and Notation, Version 2.0.2, December 2013

I get a stack trace..

/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-omg-1.7.1/lib/relaton_omg/scrapper.rb:63:in `fetch_abstract': undefined method `text' for nil:NilClass (NoMethodError)
    from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-omg-1.7.1/lib/relaton_omg/scrapper.rb:33:in `item'
    from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-omg-1.7.1/lib/relaton_omg/scrapper.rb:15:in `scrape_page'
    from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-omg-1.7.1/lib/relaton_omg/omg_bibliography.rb:10:in `search'
```

@andrew2net can you please help here? Is this a version issue since we recently just fixed this?

**Comment by andrew2net** [comment]
OMG site's layout has been changed. Relaton-OMG supports the new layout from version 1.7.2. The last version of relaton-omg is 1.7.3
