### ISSUE TITLE
(URGENT) Crash in relaton-render

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#206]
From https://github.com/metanorma/rfc-camelot-holy-grenade/pull/17

```
wrong number of arguments (given 3, expected 2)
metanorma-ietf-3.3.3/lib/relaton/render/fields.rb:19:in `dateformat'
relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:58:in `block in date_fields_format'
relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:57:in `each'
relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:57:in `date_fields_format'
relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:13:in `compound_fields_format'
metanorma-ietf-3.3.3/lib/relaton/render/fields.rb:25:in `compound_fields_format'
relaton-render-0.7.5/lib/relaton/render/general/render.rb:164:in `parse'
```

**Comment by opoudjis** [comment]
Already fixed in https://github.com/metanorma/metanorma-ietf/commit/82732dcd8c14745657b048e3a9fa5b938651a9d7
