### ISSUE TITLE
(URGENT) Any usage of `stem` crashes Metanorma IETF (only crashing flavor)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf#217]
This is a regression, the document used to work with Metanorma-IETF.

Document:
* https://github.com/CalConnect/cc-vobject-integrity

Relevant snippet:

```adoc
WHIRLPOOL is a hash function that operates on messages less than stem:[2^{256}]
bits in length, and produces a hash value of 512 bits <<WHIRLPOOL>>.
```

Error:

```
[plurimath] Error: Failed to parse the following formula with type `asciimath`.
[plurimath] Please first manually validate the formula.
[plurimath] If this is a bug, please report the formula at our issue tracker at:
[plurimath] https://github.com/plurimath/plurimath/issues
---- FORMULA BEGIN ----
<math xmlns="http://www.w3.org/1998/Math/MathML">    <mstyle displaystyle="false">      <msup>        <mn>2</mn>        <mn>256</mn>      </msup>    </mstyle> </math><asciimath>2^{256}</asciimath>
---- FORMULA END ----
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/plurimath-0.8.17/lib/plurimath/math.rb:70:in `parse_error!'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/plurimath-0.8.17/lib/plurimath/math/formula.rb:326:in `parse_error!'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/plurimath-0.8.17/lib/plurimath/math/formula.rb:48:in `rescue in to_asciimath'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/plurimath-0.8.17/lib/plurimath/math/formula.rb:44:in `to_asciimath'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-ietf-3.4.0/lib/isodoc/ietf/inline.rb:62:in `stem_parse'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/isodoc-2.12.3/lib/isodoc/function/to_word_html.rb:191:in `parse'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-ietf-3.4.0/lib/isodoc/ietf/blocks.rb:17:in `block (2 levels) in para_parse'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.17.0-arm64-darwin/lib/nokogiri/xml/node_set.rb:237:in `block in each'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.17.0-arm64-darwin/lib/nokogiri/xml/node_set.rb:236:in `upto'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.17.0-arm64-darwin/lib/nokogiri/xml/node_set.rb:236:in `each'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-ietf-3.4.0/lib/isodoc/ietf/blocks.rb:17:in `block in para_parse'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.17.0-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.17.0-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-ietf-3.4.0/lib/isodoc/ietf/blocks.rb:12:in `para_parse'
```

**Comment by ronaldtse** [comment]
Can be reproduced with:
* https://github.com/CalConnect/cc-vobject-integrity/pull/2

**Comment by opoudjis** [comment]
Compilation is still crashing, but not on MathML:

````
RFC XML: Line 000559:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000564:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000584:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000585:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000594:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000595:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000596:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000597:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000598:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000599:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000602:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000603:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000606:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000607:108 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000608:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000611:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000612:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000615:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000616:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000619:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000623:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 000624:48 attribute "id" not allowed here; expected attribute "anchor", "derivedCounter", "pn", "xml:base" or "xml:lang"
RFC XML: Line 001105:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001109:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001115:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001117:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 000646:2537 IDREF "STREEBOG" without matching ID
RFC XML: Line 000646:2869 IDREF "STREEBOG" without matching ID
RFC XML: Line 000709:191 IDREF "STREEBOG" without matching ID
RFC XML: Line 000711:211 IDREF "STREEBOG" without matching ID
RFC XML: Line 000646:4327 IDREF "SM3" without matching ID
RFC XML: Line 000681:93 IDREF "SM3" without matching ID
RFC XML: Line 000716:94 IDREF "BLAKE2" without matching ID
RFC XML: Line 000761:591 IDREF "RIPEMD160" without matching ID
RFC XML: Line 000646:2282 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000674:208 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000676:208 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000694:141 IDREF "KECCAK" without matching ID
RFC XML: Line 000716:280 IDREF "BLAKE" without matching ID
RFC XML: Line 000065:47 IDREF "vCard21" without matching ID
RFC XML: Line 000084:132 IDREF "CALCONNECT-VCARD" without matching ID
RFC XML: Line 000084:192 IDREF "CALCONNECT-CALENDAR" without matching ID
RFC XML: xref target vCard21 does not exist in the document
RFC XML: xref target CALCONNECT-VCARD does not exist in the document
RFC XML: xref target CALCONNECT-CALENDAR does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target SM3 does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target SM3 does not exist in the document
RFC XML: xref target KECCAK does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target BLAKE2 does not exist in the document
RFC XML: xref target BLAKE does not exist in the document
RFC XML: xref target RIPEMD160 does not exist in the document
````

**Comment by opoudjis** [comment]
Changing `li/@id` to `li/@anchor`

**Comment by opoudjis** [comment]
xref errors now remain, and are presumably a content issue:

````
RFC XML: Line 001105:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001109:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001115:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 001117:112 character content of element "stream" invalid; must be equal to "IAB", "IETF", "IRTF" or "independent"
RFC XML: Line 000646:2537 IDREF "STREEBOG" without matching ID
RFC XML: Line 000646:2869 IDREF "STREEBOG" without matching ID
RFC XML: Line 000709:191 IDREF "STREEBOG" without matching ID
RFC XML: Line 000711:211 IDREF "STREEBOG" without matching ID
RFC XML: Line 000646:4327 IDREF "SM3" without matching ID
RFC XML: Line 000681:93 IDREF "SM3" without matching ID
RFC XML: Line 000716:94 IDREF "BLAKE2" without matching ID
RFC XML: Line 000761:591 IDREF "RIPEMD160" without matching ID
RFC XML: Line 000646:2282 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000674:208 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000676:208 IDREF "WHIRLPOOL" without matching ID
RFC XML: Line 000694:141 IDREF "KECCAK" without matching ID
RFC XML: Line 000716:280 IDREF "BLAKE" without matching ID
RFC XML: Line 000065:47 IDREF "vCard21" without matching ID
RFC XML: Line 000084:132 IDREF "CALCONNECT-VCARD" without matching ID
RFC XML: Line 000084:192 IDREF "CALCONNECT-CALENDAR" without matching ID
RFC XML: xref target vCard21 does not exist in the document
RFC XML: xref target CALCONNECT-VCARD does not exist in the document
RFC XML: xref target CALCONNECT-CALENDAR does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target SM3 does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target WHIRLPOOL does not exist in the document
RFC XML: xref target SM3 does not exist in the document
RFC XML: xref target KECCAK does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target STREEBOG does not exist in the document
RFC XML: xref target BLAKE2 does not exist in the document
RFC XML: xref target BLAKE does not exist in the document
RFC XML: xref target RIPEMD160 does not exist in the document
````
