### ISSUE TITLE
Compiling fail

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-ietf#45]
I tried compile document and got error:
```
$ metanorma --type ietf spec/examples/example-v3.adoc
asciidoctor: WARNING (??): suffix "Working Group" will be stripped in published RFC from Network Working Group
asciidoctor: WARNING (??): unrecognised working group Network Working Group
[metanorma-ietf] value of attribute "category" is invalid; must be equal to "bcp", "exp", "historic", "info" or "std" @ 11:135
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 62:46
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 99:52
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 107:74
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 114:62
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 132:70
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 133:74
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 145:76
[metanorma-ietf] found attribute "quote-title", but no attributes allowed here @ 152:88
[metanorma-ietf] found attribute "quote-title", but no attributes allowed here @ 177:76
asciidoctor: WARNING (??): suffix "Working Group" will be stripped in published RFC from Network Working Group
asciidoctor: WARNING (??): unrecognised working group Network Working Group
[metanorma-ietf] attribute "quote-title" not allowed here; expected attribute "quoteTitle", "xml:base" or "xml:lang" @ 171:88
[metanorma-ietf] attribute "quote-title" not allowed here; expected attribute "quoteTitle", "xml:base" or "xml:lang" @ 197:76
/Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:133:in `initialize': No such file or directory @ rb_sysopen - /var/folders/qf/c8zl30p57pq5p7n1l5znydl80000gn/T/spec/examples/example-v3.html20191119-67673-5qpcay (Errno::ENOENT)
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:133:in `open'
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:133:in `block in initialize'
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tmpdir.rb:130:in `create'
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:291:in `new'
	from /Users/andrej/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:291:in `open'
	from /Users/andrej/RubyProjects/metanorma-ietf/lib/metanorma/ietf/processor.rb:71:in `output'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:192:in `block in process_extensions'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:183:in `each'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:183:in `process_extensions'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.18/lib/metanorma/compile.rb:20:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/lib/metanorma/cli/compiler.rb:29:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/lib/metanorma/cli/compiler.rb:33:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/lib/metanorma/cli/command.rb:34:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/lib/metanorma/cli.rb:60:in `start'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7.3/exe/metanorma:20:in `<top (required)>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/metanorma:23:in `load'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/metanorma:23:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `<main>'
```
Tested on ruby-2.4.0

**Comment by opoudjis** [comment]
I can't replicate this:

````
~/Documents/Arbeit/upwork/ribose/metanorma-ietf[master] $ metanorma --type ietf spec/examples/example-v3.adoc
asciidoctor: WARNING (??): suffix "Working Group" will be stripped in published RFC from Network Working Group
asciidoctor: WARNING (??): unrecognised working group Network Working Group
[metanorma-ietf] value of attribute "category" is invalid; must be equal to "bcp", "exp", "historic", "info" or "std" @ 11:135
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 62:46
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 99:52
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 107:74
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 114:62
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 132:70
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 133:74
[metanorma-ietf] attribute "numbered" not allowed here; expected attribute "toc" @ 145:76
[metanorma-ietf] found attribute "quote-title", but no attributes allowed here @ 152:88
[metanorma-ietf] found attribute "quote-title", but no attributes allowed here @ 177:76
asciidoctor: WARNING (??): suffix "Working Group" will be stripped in published RFC from Network Working Group
asciidoctor: WARNING (??): unrecognised working group Network Working Group
[metanorma-ietf] attribute "quote-title" not allowed here; expected attribute "quoteTitle", "xml:base" or "xml:lang" @ 171:88
[metanorma-ietf] attribute "quote-title" not allowed here; expected attribute "quoteTitle", "xml:base" or "xml:lang" @ 197:76
Parsing file /var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/specexamplesexample-v3.html20191210-50151-186x7h0
Warning: No DTD given, defaulting to /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd
Error: Unable to validate the XML document: /var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/specexamplesexample-v3.html20191210-50151-186x7h0
 <string>: Line 11: Value "full-standard 1149" for attribute category of rfc is not among the enumerated set
Parsing file /var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/specexamplesexample-v3.txt20191210-50151-10bevb9
Warning: No DTD given, defaulting to /usr/local/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd
Error: Unable to validate the XML document: /var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/specexamplesexample-v3.txt20191210-50151-10bevb9
 <string>: Line 11: Value "full-standard 1149" for attribute category of rfc is not among the enumerated set
~/Documents/Arbeit/upwork/ribose/metanorma-ietf[master] $ vi /var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/specexamplesexample-v3.txt20191210-50151-10bevb9
````

**Comment by opoudjis** [comment]
Innnteresting. I could not replicate for Ruby 2.5.1, but I have for Ruby 2.4.0. Investigating.

**Comment by opoudjis** [comment]
Got it. In Ruby 2.4, but not Ruby 2.5, the basename of a Tempfile must actually be a base name, and it is being passed a full path if compiled in a separate subdirectory: spec/examples/example-v3.adoc is not a legal Tempfile basename in Ruby 2.4.
